### ISSUE TITLE
Appearance dark does not seem to do anything.

### ISSUE THREAD

**Issue by dnasseri** [riggraz/no-style-please#18]
Hello there. I have a basic setup with this theme, and I'm noticing that the specifying "dark" will not change the color scheme of the theme when building. I have the following _config.yml

```
title: nassredean nasseri
tagline: "| nasseri.io"
author:
  name: Nassredean Nasseri
email: dean@nasseri.io
description: "the personal website of nassredean nasseri"
url: "https://nasseri.io"
baseurl: ""
exclude: [scripts/]
favicon: "favicon.png"
permalink: /:slug.html
theme: no-style-please
theme_config:
  appearance: "dark"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page
timezone: America/New_York
plugins:
  - jekyll-sitemap
  - jekyll-feed
```

I observe that the `<body>` tag, is not being given an `a` attribute of any kind after running `jekyll build`. So it seems like, somehow this line `<body a="{{ site.theme_config.appearance | default: "auto" }}">` in https://github.com/riggraz/no-style-please/blob/3432e31045f14ee57dedd1e0653c3d94d19eed01/_layouts/default.html is not working for me.

Is there anything else I need to do to get the dark theme applying correctly? Note that I have no _layouts, _includes, or _posts directory in my site. Not sure if that makes a difference.
