### ISSUE TITLE
"mailto" does not work

### ISSUE THREAD

**Issue by yzhou216** [riggraz/no-style-please#56]
data/menu.toml:

```toml
title = "email"
url = "mailto:user@example.com"
```

When hyperlink is clicked, the pages goes to 404 and the URL displays as `https://example.com/mailto:user@example.com`
