### ISSUE TITLE
custom css for `a` tag isn't working

### ISSUE THREAD

**Issue by thebigbone** [riggraz/no-style-please#86]
hello, I recently migrated to your theme and it's really awesome. I tried to remove the underline in `a` tag by adding:
```css
a {
  text-decoration: none;
}
```
in `no-style-please.scss`. but it's not applying that change. is there anything which is overriding those changes?
